language: php

php: 
  - 7.0
  - 7.1
  - 7.2

services:
  - mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - travis_retry composer install

script: vendor/bin/phpunit --verbose

notifications:
  email:
    on_success: [never]
